function generateCloudRunTerraform(application) {

    return {

        "provider.tf": `
provider "google" {
  project = var.gcp_project
  region  = var.region
}
`,

        "versions.tf": `
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "velocity-terraform-state"
    prefix = "applications/${application.applicationName}"
  }
}
`,

        "variables.tf": `
variable "gcp_project" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region"
  type        = string
}

variable "application_name" {
  description = "Application name"
  type        = string
}

variable "container_image" {
  description = "Container image"
  type        = string
}
`,

        "main.tf": `
resource "google_project_service" "run" {
  project = var.gcp_project
  service = "run.googleapis.com"

  disable_on_destroy = false
}

resource "google_cloud_run_v2_service" "app" {

  name     = var.application_name
  location = var.region

  deletion_protection = false

  template {

    containers {

      image = var.container_image

      ports {
        container_port = 8080
      }

    }

  }

  depends_on = [
    google_project_service.run
  ]
}
`,

        "outputs.tf": `
output "application_name" {
  value = google_cloud_run_v2_service.app.name
}

output "service_url" {
  value = google_cloud_run_v2_service.app.uri
}
`,

"terraform.tfvars.example": `
gcp_project      = "YOUR_GCP_PROJECT_ID"
region           = "${application.region}"
application_name = "${application.applicationName}"
container_image  = "us-docker.pkg.dev/cloudrun/container/hello"
`,

        "README.md": `
# ${application.applicationName}

Generated by Velocity Platform.

## Cloud

${application.cloud}

## Region

${application.region}

## Service

Cloud Run

## Terraform

This infrastructure was generated automatically by Velocity.
`
    };
}

module.exports = {
    generateCloudRunTerraform
};