function generateCloudRunTerraform(application) {
  return {
    "provider.tf": `
provider "google" {
  project = var.gcp_project
  region  = var.region
}
`.trim(),

    "versions.tf": `
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "velocity-terraform-state"
    prefix = "applications/${application.applicationName}"
  }
}
`.trim(),

    "variables.tf": `
variable "gcp_project" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region"
  type        = string
}

variable "application_name" {
  description = "Application name"
  type        = string
}

variable "application_owner" {
  description = "Application owner"
  type        = string
}

variable "environment" {
  description = "Deployment environment"
  type        = string
}

variable "container_image" {
  description = "Container image"
  type        = string
}
`.trim(),

    "main.tf": `
resource "google_cloud_run_v2_service" "app" {
  name     = var.application_name
  location = var.region

  labels = {
    managed-by              = "cloudops"
    application             = lower(var.application_name)
    application-owner       = lower(var.application_owner)
    infrastructure-operator = "gisocc"
    environment             = lower(var.environment)
    platform                = "internal-developer-platform"
  }

  deletion_protection = false

  template {
    containers {
      image = var.container_image

      ports {
        container_port = 8080
      }
    }
  }
}
`.trim(),

    "outputs.tf": `
output "application_name" {
  value = google_cloud_run_v2_service.app.name
}

output "service_url" {
  value = google_cloud_run_v2_service.app.uri
}
`.trim(),

    "terraform.tfvars": `
gcp_project       = "${process.env.GCP_PROJECT_ID}"
region            = "${application.region}"
application_name  = "${application.applicationName}"
application_owner = "${application.owner}"
environment       = "${application.environment}"
container_image   = "${process.env.CONTAINER_IMAGE || "us-docker.pkg.dev/cloudrun/container/hello"}"
`.trim(),

    "terraform.tfvars.example": `
gcp_project       = "YOUR_GCP_PROJECT_ID"
region            = "${application.region}"
application_name  = "${application.applicationName}"
application_owner = "APPLICATION_OWNER"
environment       = "${application.environment}"
container_image   = "us-docker.pkg.dev/cloudrun/container/hello"
`.trim(),

    "README.md": `
# ${application.applicationName}

Generated by Velocity Platform.

## Cloud

${application.cloud}

## Region

${application.region}

## Service

Cloud Run

## Terraform

This infrastructure was generated automatically by Velocity.
`.trim()
  };
}

module.exports = {
  generateCloudRunTerraform
};