function generateComputeEngineTerraform(application) {
    return {
        "provider.tf": `
provider "google" {
  project = var.gcp_project
  region  = var.region
  zone    = var.zone
}
`.trim(),

        "versions.tf": `
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "velocity-terraform-state"
    prefix = "applications/${application.applicationName}"
  }
}
`.trim(),

        "variables.tf": `
variable "gcp_project" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region"
  type        = string
}

variable "zone" {
  description = "GCP availability zone"
  type        = string
}

variable "application_name" {
  description = "Application name"
  type        = string
}

variable "application_owner" {
  description = "Application owner"
  type        = string
}

variable "environment" {
  description = "Deployment environment"
  type        = string
}

variable "machine_type" {
  description = "Compute Engine machine type"
  type        = string
  default     = "e2-medium"
}

variable "boot_image" {
  description = "Boot disk image"
  type        = string
  default     = "projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts"
}
`.trim(),

        "main.tf": `
resource "google_compute_instance" "app" {
  name         = var.application_name
  machine_type = var.machine_type
  zone         = var.zone

  boot_disk {
    initialize_params {
      image = var.boot_image
    }
  }

  network_interface {
    network = "default"

    access_config {}
  }

  labels = {
    managed-by               = "cloudops"
    application              = var.application_name
    application-owner        = var.application_owner
    infrastructure-operator  = "gisocc"
    environment              = var.environment
    platform                 = "internal-developer-platform"
  }

  tags = [
    "velocity",
    var.environment
  ]
}
`.trim(),

        "outputs.tf": `
output "instance_name" {
  value = google_compute_instance.app.name
}

output "instance_id" {
  value = google_compute_instance.app.id
}

output "instance_self_link" {
  value = google_compute_instance.app.self_link
}

output "internal_ip" {
  value = google_compute_instance.app.network_interface[0].network_ip
}

output "external_ip" {
  value = google_compute_instance.app.network_interface[0].access_config[0].nat_ip
}
`.trim(),

        "terraform.tfvars": `
gcp_project      = "${process.env.GCP_PROJECT_ID}"
region           = "${application.region}"
zone             = "${application.region}-a"
application_name = "${application.applicationName}"
application_owner = "${application.owner}"
environment      = "${application.environment}"
machine_type     = "e2-medium"
`.trim(),

        "terraform.tfvars.example": `
gcp_project       = "YOUR_GCP_PROJECT_ID"
region            = "${application.region}"
zone              = "${application.region}-a"
application_name  = "${application.applicationName}"
application_owner = "${application.owner}"
environment       = "${application.environment}"
machine_type      = "e2-medium"
`.trim(),

        "README.md": `
# ${application.applicationName}

Generated by Velocity Platform.

## Application

${application.applicationName}

## Owner

${application.owner}

## Team

${application.team}

## Cloud

GCP

## Region

${application.region}

## Environment

${application.environment}

## Service

Compute Engine

Infrastructure generated automatically by Velocity.
`.trim()
    };
}

module.exports = {
    generateComputeEngineTerraform
};