const {
    generatePipeline
} = require("../pipelines/pipelineGenerator");


function generateRepository(
    application,
    terraform
) {

    return {

        /*
         * Terraform files
         */

        ...terraform,


        /*
         * GitHub Actions
         */

        ".github/workflows/terraform.yml":
            generatePipeline(application),


        /*
         * Git configuration
         */

        ".gitignore":
            generateGitignore(),


        /*
         * Velocity metadata
         */

        "velocity.yaml":
            generateVelocityMetadata(application),


        /*
         * Documentation
         */

        "README.md":
            generateReadme(application),
    };
}


/*
 * =========================================================
 * VELOCITY METADATA
 * =========================================================
 */

function generateVelocityMetadata(application) {

    const isGCP =
        application.cloud === "GCP";

    const cloudConfiguration =
        isGCP
            ? `
  provider: GCP
  project: ${process.env.GCP_PROJECT_ID || "configured-in-github"}
  region: ${application.region}
`
            : `
  provider: AWS
  region: ${application.region}
  authentication: GitHub OIDC
  role: ${process.env.AWS_ROLE_ARN || "configured-in-github"}
`;


    return `application:
  name: ${application.applicationName}
  owner: ${application.owner}
  team: ${application.team}

cloud:${cloudConfiguration}
service:
  type: ${application.service}

environment:
  name: ${application.environment}

terraform:
  state_backend: local
  state_prefix: applications/${application.applicationName}

managed_by: Velocity
`;
}


/*
 * =========================================================
 * README
 * =========================================================
 */

function generateReadme(application) {

    return `# ${application.applicationName}

Infrastructure repository generated by **Velocity Internal Developer Platform**.

---

## Application

| Property | Value |
|---|---|
| Application | ${application.applicationName} |
| Owner | ${application.owner} |
| Team | ${application.team} |
| Cloud | ${application.cloud} |
| Region | ${application.region} |
| Environment | ${application.environment} |
| Service | ${application.service} |

---

## Terraform

This repository contains infrastructure-as-code generated by Velocity.

### Validate locally

\`\`\`bash
terraform fmt -check -recursive
terraform init
terraform validate
terraform plan
\`\`\`

---

## GitHub Actions

The repository contains:

\`.github/workflows/terraform.yml\`

The pipeline performs:

1. Terraform format validation
2. Terraform initialization
3. Terraform validation
4. Terraform plan
5. Terraform apply through the protected \`production\` environment

---

## Authentication

${application.cloud === "AWS"
        ? `
AWS authentication uses GitHub Actions OpenID Connect (OIDC).

No long-lived AWS access keys are stored in the repository.
`
        : `
GCP authentication uses GitHub Actions Workload Identity Federation.

No long-lived GCP service account key is stored in the repository.
`
}

---

## Managed By

Velocity Internal Developer Platform
`;
}


/*
 * =========================================================
 * GITIGNORE
 * =========================================================
 */

function generateGitignore() {

    return `.terraform/
.terraform.lock.hcl

*.tfstate
*.tfstate.*
crash.log
*.tfplan

override.tf
override.tf.json
*_override.tf
*_override.tf.json

.DS_Store
`;
}


module.exports = {
    generateRepository
};