const {
    generatePipeline
} = require("../pipelines/pipelineGenerator");

function generateRepository(application, terraform) {

    return {
    ...terraform,

    ".github/workflows/terraform.yml":
        generatePipeline(application),

    ".gitignore":
        generateGitignore(),

    "velocity.yaml":
        generateVelocityMetadata(application),

    "README.md":
        generateReadme(application)
};
}

function generateVelocityMetadata(application) {

    const cloudConfiguration =
        application.cloud === "GCP"
            ? `
  provider: GCP
  project: ${process.env.GCP_PROJECT_ID}
  region: ${application.region}
`
            : `
  provider: AWS
  region: ${application.region}
`;


    return `application:
  name: ${application.applicationName}
  owner: ${application.owner}
  team: ${application.team}

cloud:
${cloudConfiguration.trimEnd()}

service:
  type: ${application.service}

terraform:
  state_prefix: applications/${application.applicationName}
`;
}


function generateReadme(application) {

    return `# ${application.applicationName}

Generated by Velocity Platform.

## Application

${application.applicationName}

## Owner

${application.owner}

## Team

${application.team}

## Cloud

${application.cloud}

## Region

${application.region}

## Environment

${application.environment}

## Service

${application.service}

---

Infrastructure generated automatically by Velocity.
`;
}

function generateGitignore() {

    return `.terraform/
*.tfstate
*.tfstate.*
crash.log
*.tfplan
`;
}

module.exports = {
    generateRepository
};