function generateRepository(application, terraform) {

    return {

        "README.md": generateReadme(application),

        ".gitignore": generateGitignore(),

        ".github/workflows/terraform.yml": generatePipeline(application),

        ...terraform

    };

}

function generateReadme(application) {

    return `# ${application.applicationName}

Generated by Velocity

## Cloud

${application.cloud}

## Region

${application.region}

## Service

${application.service}

Generated automatically by Velocity Platform.
`;

}

function generateGitignore() {

    return `.terraform/

*.tfstate

*.tfstate.*

crash.log

terraform.tfvars`;

}

const {

generatePipeline

} = require("../pipelines/pipelineGenerator");

module.exports = {

    generateRepository

};